---
title: "Github Projects"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(shiny)
```

The cards below detail the various repos and projects I am working on that are available on Github. Click on the links to learn more!

```{r}
column(
  width = 6,
  div(
    class="github_proj",
    tags$a(h2("mSHAP"), href = "https://github.com/srmatth/mshap"),
    p("The github project that houses the mSHAP R package, and also includes code that accompanies the paper mSHAP: SHAP Values for Two-Part Models (Matthews and Hartman, 2021)")
  ),
  div(
    class="github_proj",
    tags$a(h2("historicalInvesting"), href = "https://github.com/srmatth/historicalInvesting"),
    p("The Historical Investing app allows users to enter amounts invested in an arbitrary number of stocks of their choice at a past date (including recurring deposits and reinvesting dividends) and to see what the value of that portfolio would be today. It is most useful in the creation and customization of historical stock charts.")
  ),
  div(
    class="github_proj",
    tags$a(h2("valueInvesting"), href = "https://github.com/srmatth/value.investing"),
    p("A basic website displaying reports created for different industries, with the attempt to predict five year stock price growth for the stocks in each industry. Not professional advice at all, just fun to look at.")
  )
)
column(
  width = 6,
  div(
    class="github_proj",
    tags$a(h2("tidytuesday"), href = "https://github.com/srmatth/tidytuesday"),
    p("My attempts at honing my data visualization skills via the weekly dataset put out in the tidytuesday repo from rfordatascience")
  ),
  div(
    class="github_proj",
    h2("CAS"),
    p("Code that accompanies the paper: An Exploration of two-part models for CAS datasets.")
  ),
  div(
    class="github_proj",
    tags$a(h2("srmatth.github.io"), href = "https://github.com/srmatth/srmatth.github.io"),
    p("See the HTML code used to create this website!")
  )
)
```


<!--
<div class="col_4">
  <div class="github_proj">
    mSHAP
  </div>
  <div class="github_proj">
    tidytuesday
  </div>
</div>

<div class="col_4">
  <div class="github_proj">
    historicalInvesting
  </div>
  <div class="github_proj">
    srmatth.github.io
  </div>
</div>

<div class="col_4">
  <div class="github_proj">
    CAS
  </div>
  <div class="github_proj">
    valueInvesting
  </div>
</div>

-->