---
title: "<div style='text-align:right; font-size:14pt;'><a href='portfolio.html'>Back to Portfolio Home</a></div>Paper Portfolio"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(shiny)
```

```{css}
h2, h3, h4, h5, h6{
  text-align:center;
}
```

A list of papers/writing I have contributed to, ordered by descending date.

<hr style="border-top: 1px solid black">

## Machine Learning in Ratemaking, an Application in Commercial Auto Insurance (April 2022) {#ml_in_ratemaking}

<div class='col_4' style='text-align:center'>
  <a href="https://doi.org/10.3390/risks10040080">
    <i class="fas fa-external-link-alt" style="font-size:30pt"></i>
    <br>
    View the Published Paper Online
  </a>
</div>

<div class='col_4' style='text-align:center'>
  <a href="resources/cas_published.pdf">
    <i class="fas fa-file-download" style="font-size:30pt"></i>
    <br>
    Download a PDF of the Paper
  </a>
</div>

<div class='col_4' style='text-align:center'>
  <a href="https://github.com/srmatth/CAS">
    <i class="fab fa-github" style="font-size:30pt"></i>
    <br>
    View the Accompanying GitHub Repo
  </a>
</div>

## Abstract

This paper explores the tuning and results of two-part models on rich datasets provided through the Casualty Actuarial Society (CAS). These datasets include bodily injury (BI), property damage (PD) and collision (COLL) coverage, each documenting policy characteristics and claims across a four-year period. The datasets are explored, including summaries of all variables, then the methods for modeling are set forth. Models are tuned and the tuning results are displayed, after which we train the final models and seek to explain select predictions. Data were provided by a private insurance carrier to the CAS after anonymizing the dataset. These data are available to actuarial researchers for well-defined research projects that have universal benefit to the insurance industry and the public. Our hope is that the methods demonstrated here can be a good foundation for future ratemaking models to be developed and tested more efficiently.

<hr style="border-top: 1px solid black">

## Spatial Analysis of Chlorophyll Concentration (March 2022) {#stat_295_spatial}

<div class='col_12' style='text-align:center'>
  <a href="resources/spatial_final.pdf">
    <i class="fas fa-file-download" style="font-size:30pt"></i>
    <br>
    Download a PDF of the Final Project
  </a>
</div>

## Abstract

This final project aimed to apply the methods learned for spatial data analysis to a dataset of our choosing.
I analyzed chlorophyll concentration (a proxy for phytoplankton presence) in the Indian Ocean in the Summer of 2021.
Various covariates were obtained including depth, coral presence, temperature, and salinity.
Residual spatial correlation remained.
Random spatial effects were estimated using Bayesian procedures, and predictions were made for different time periods to test the effectiveness of our model.

<hr style="border-top: 1px solid black">

## Data Analysis: ESRD Access Type (March 2022) {#stat_211}

<div class='col_12' style='text-align:center'>
  <a href="resources/211_final.pdf">
    <i class="fas fa-file-download" style="font-size:30pt"></i>
    <br>
    Download a PDF of the Final Project
  </a>
</div>

## Abstract

Data on over 1,500 dialysis patients in the United States were analyzed with the outcome of interest being the revision rate on dialysis accesses placed in the patient.
Models were constructed to determine the effect of access type of revision rate.
Both venous transposition arteriovenous fistula accesses and prosthetic graft accesses had higher revision rates than standard arteriovenous fistula accesses (68\%, CI = (22\%, 132\%) and 93\%, CI = (58\%, 135\%), respectively).
No difference in revision rate was found between arteriovenous fistula accesses and prosthetic graft accesses.
The difference in revision rate by access type is different across diabetic status, but not by age.
Models were also constructed to accurately predict revision rates in a patient receiving their first access, and predictions presented.

<hr style="border-top: 1px solid black">


## mSHAP: SHAP Values for Two-Part Models (January 2022) {#mshap}

<div class='col_6' style='text-align:center'>
  <a href="https://doi.org/10.3390/risks10010003">
    <i class="fas fa-external-link-alt" style="font-size:30pt"></i>
    <br>
    View the Published Paper Online
  </a>
</div>

<div class='col_6' style='text-align:center'>
  <a href="resources/mSHAP_published.pdf">
    <i class="fas fa-file-download" style="font-size:30pt"></i>
    <br>
    Download a PDF of the Paper
  </a>
</div>

## Abstract

Two-part models are important to and used throughout insurance and actuarial science. Since insurance is required for registering a car, obtaining a mortgage, and participating in certain businesses, it is especially important that the models that price insurance policies are fair and non-discriminatory. Black box models can make it very difficult to know which covariates are influencing the results, resulting in model risk and bias. SHAP (SHapley Additive exPlanations) values enable interpretation of various black box models, but little progress has been made in two-part models. In this paper, we propose mSHAP (or multiplicative SHAP), a method for computing SHAP values of two-part models using the SHAP values of the individual models. This method will allow for the predictions of two-part models to be explained at an individual observation level. After developing mSHAP, we perform an in-depth simulation study. Although the kernelSHAP algorithm is also capable of computing approximate SHAP values for a two-part model, a comparison with our method demonstrates that mSHAP is exponentially faster. Ultimately, we apply mSHAP to a two-part ratemaking model for personal auto property damage insurance coverage. Additionally, an R package (mshap) is available to easily implement the method in a wide variety of applications.

<hr style="border-top: 1px solid black">

## Infectious Disease Final Project (December 2021) {#stat_295}

<div class='col_12' style='text-align:center'>
  <a href="resources/Infectious_Disease_Final_Project.pdf">
    <i class="fas fa-file-download" style="font-size:30pt"></i>
    <br>
    Download a PDF of the Project
  </a>
</div>

## Abstract

This project was completed jointly with Anthony Hu, a fellow statistics student at UC Irvine in the fall semester of 2021 for STATS 295, Statistical Methods for Infectious Disease Data.
In this project, we outline and then replicate a paper discussing Rotavirus vaccinations in a specific region of Spain.
We additionally apply the method used in the paper to new data on COVID-19 hospitaliations in New York, Georgia, and Virginia.

<hr style="border-top: 1px solid black">

<!--
## NDSEG Proposal 2021 (November 2021) {#ndseg_prop}

<div class='col_12' style='text-align:center'>
  <a href="resources/NDSEG_2021_Proposal.pdf">
    <i class="fas fa-file-download" style="font-size:30pt"></i>
    <br>
    Download a PDF of the Proposal
  </a>
</div>

## Abstract

This proposal was submitted to the NDSEG Fellowship in November of 2021, and was written with the aid of Dr. Michele Guindani, Dr. Richard Warr, and Dr. Aaron Bornstein.
It outlines a method for using statistical methods to improve brain functionality mapping during decisions involving some level of risk, with the ultimate goal being to understand how humans make decisions under risk.
Furthermore, we propose a method for leveraging the information gained from the mapping to inform better real-world predictions by creating a machine learning algorithm structured after the networks the human brain uses to make these computations.

<hr style="border-top: 1px solid black">
-->

