---
title: "Research"
output: html_document
---

My research interests include natural language processing, explainable machine learning, astrostatistics, and statistical computing.
Following are papers and presentations that came from original research.

<hr style="border-top: 1px solid black">

## <a href="research-mshap.html">mSHAP</a>

**Published in *Risks*, January 2022**

*Joint work with Brian Hartman*

Two-part models are important to and used throughout insurance and actuarial science. 
Since insurance is required for registering a car, obtaining a mortgage, and participating in certain businesses, it is especially important that the models which price insurance policies are fair and non-discriminatory. 
mSHAP is a methodology for explaining the predictions of these two-part models to ensure accuracy and fairness in setting insurance prices.

<hr style="border-top: 1px solid black">

## <a href="research-cas.html">CAS Data</a>

**In Progress**

*Joint work with Brian Hartman*

Due to privacy and proprietary property concerns, there are not many insurance data sets available to those in the data field.
In this project, we obtained a large data set of policies and explored the possibilities of predicting the premium using two-part models made up of many different machine learning algorithms.
This data is now available from the CAS (Casualty Actuary Society) and this project includes a user guide for the data.

<hr style="border-top: 1px solid black">



